# compose.yml
services:
  site:
    build: .
    ports:
      - "127.0.0.1:4322:4321"
    environment:
      - TEA_ADMIN_EMAIL_1=${TEA_ADMIN_EMAIL_1:-}
      - TEA_ADMIN_PASSWORD_1=${TEA_ADMIN_PASSWORD_1:-}
      - TEA_ADMIN_EMAIL_2=${TEA_ADMIN_EMAIL_2:-}
      - TEA_ADMIN_PASSWORD_2=${TEA_ADMIN_PASSWORD_2:-}
    volumes:
      - ./tea_data:/app/data
