import { get, post, route } from "remix/routes";

export const routes = route({
  assets: get("/assets/*path"),
  home: get("/"),
  health: get("/healthz"),
  sitemap: get("/sitemap.xml"),
  robots: get("/robots.txt"),
  page: get("/*slug"),
  file: get("/tea/api/media/file/:id"),
  auth: route("/tea", {
    login: get("/login"),
    authenticate: post("/login"),
    logout: post("/logout"),
  }),
  admin: route("/tea/admin", {
    index: get("/"),
    pages: get("/pages"),
    createPage: post("/pages"),
    edit: get("/pages/:slug"),
    save: post("/pages/:slug"),
    publish: post("/pages/:slug/publish"),
    deletePage: post("/pages/:slug/delete"),
    homepage: get("/homepage"),
    saveHomepage: post("/homepage"),
    publishHomepage: post("/homepage/publish"),
    media: get("/media"),
    upload: post("/media"),
    updateMedia: post("/media/:id"),
    deleteMedia: post("/media/:id/delete"),
    saveFolder: post("/folders"),
    deleteFolder: post("/folders/:id/delete"),
    sidebar: get("/sidebar"),
    saveSidebar: post("/sidebar"),
    adornments: get("/adornments"),
    saveAdornment: post("/adornments"),
    deleteAdornment: post("/adornments/:id/delete"),
    site: get("/site"),
    saveSite: post("/site"),
    seo: get("/seo"),
    preview: post("/preview"),
    history: get("/history/:id"),
  }),
});
